name: PR review

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: setup firebase options
        run: |
          cat <<EOF > front/lib/firebase_options.dart
          ${{ secrets.FIREBASE_OPTIONS }}
          EOF
      - name: Install dependencies
        run: |
          cd front
          flutter pub get
      - uses: invertase/github-action-dart-analyzer@v1
